server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:rabc_admin}?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tenant-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# fegin
feign:
  hystrix:
    enabled: true

# mybatis-plus
mybatis-plus:
  typeEnumsPackage: com.csp.github.*.enums
  global-config:
    db-config:
      id-type: ID_WORKER
      logic-delete-value: 1
      logic-not-delete-value: 2
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
tenant:
  column: tenant_id
  # 多租户过滤表
  table-filters:
    - tenant
    - tenant_admin_permission_relation
    - tenant_admin_role_relation
    - tenant_role_permission_relation
