server:
  port: 11110
zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    tenant-service: /tenant/**
  ignored-services: '*'
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
spring:
  application:
    name: getway
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
