server:
  port: 11110

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    tenant-service: /tenant/**
  ignored-services: '*'
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
spring:
  application:
    name: getway
  redis:
    host: localhost
    port: 6379


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
