server:
  port: 11110

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
zuul:
  routes:
    rabc-service: /rabc/**
    ce-service: /ce/**
  ignored-services: '*'
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
spring:
  application:
    name: getway

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
