spring:
  application:
    name: xxxx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 8009

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8999/xxl-job-admin
    accessToken:
    executor:
      ip:
      appname: xxl-job-executor-sample
      port: 9999
      logpath: ./xxl-job/jobhandler
      logretentiondays: -1

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000